[tool.poetry]
name = "wplan"
version = "0.1.0"
description = ""
authors = ["valentin <piterans.v@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
pyinstaller = ">=6.17.0,<7.0.0"
aiohttp = "^3.14.3"
python-dotenv = "^1.2.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"